<legend><h2>Departamento de Bomberos</h2></legend>
<br>
<div class="hero-unit">
	<div class="datos">
		<ul>
			<li><a href="bombero/administradores">ADMINISTRADORES</a></li>
			<li><a href="bombero/supervisores">SUPERVISORES</a></li>
			<li><a href="bombero/nuevo">INGRESAR NUEVO BOMBERO</a></li>
			<li><a href="bombero/unidaa">INGRESAR NUEVA UNIDAD</a></li>
		</ul>		
	</div>
	<div class="foto">
		<img src="<?= $_layoutParams['ruta_img']?>cb.jpg" height="200px" width="180px" alt="Escudo de PolicíaBombero">
	</div>
		
</div>
<br>