<form id="usuario" class="form-horizontal" action='<?= BASE_URL; ?>bombero/ingresarAlerta/' method='post'>
  <fieldset>
  <legend>NUEVA ALERTA</legend>
  <legend>Datos Personales</legend>
    <div class="control-group">
      <label class="control-label" for="inputNUMERO">NUMERO *</label>
      <div class="controls">
        <input autofocus type="text" class="input-large"  id="inputNUMERO" name='NUMERO' required>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputNOMBRE">NOMBRES *</label>
      <div class="controls">
        <input autofocus type="text" class="input-large"  id="inputNOMBRE" name='NOMBRE' required>
      </div>
    </div>
    <legend>Datos de la Emergencia</legend>
    <div class="control-group">
      <label class="control-label" for="inputUBICACION">UBICACION *</label>
      <div class="controls">
        <input type="text" class="input-large"  id="inputUBICACION" name='UBICACION' required>
      </div>
    </div>    
    <div class="control-group">
      <label class="control-label" for="inputTIPO">TIPO DE EMERGENCIA</label>
      <div class="controls">
        <select name="TIPO" required>
          <option selected >Seleccione</option>
          <option value="3">Accidente Vehicular</option>
          <option value="4">Incendio</option>
          <option value="5">Emergencia Médica</option>
          <option value="6">Otros</option>
        </select>
      </div>
    </div> 
    <div class="control-group">
      <label class="control-label" for="inputDETALLE">DETALLE DE EMERGENCIA</label>
      <div class="controls">
        <textarea class="input-large" name="DETALLE" id="DETALLE" style="resize:none;"></textarea>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputDERIVAR">DERIVAR</label>
      <br>
      <div class="controls">

        <?php if((Session::get('distrito'))=="TODOS"):?>
        <div>
        <p>Distrito:</p>
          <select size='5'name='DISTRITO' id='distrito'>
          <option selected >Seleccione</option>
          <?php while($reg=$this->distritos->fetch_object()):?>
            <option value ='<?= $reg->District?>' ><?= $reg->NameUbigeo?></option>
            <?php endwhile;?>
          </select>
        </div>
         <?php endif; ?>

        <?php if( (Session::get('distrito'))!="TODOS"):?>
        <div>
        <p>Unidad:</p>
          <select size='5'name='UNIDAD' id='unidad'>
          <option selected>Seleccione</option>
          <?php while($reg2=$this->unidades->fetch_object()):?>
            <option value ='<?= $reg2->idAppUnit?>' ><?= $reg2->Plate?></option>
            <?php endwhile;?>
          </select>
        </div>
         <?php endif; ?>
      </div>
    </div>    
    <div class="control-group">
      <div class="controls">
        <input type='submit' class="btn btn-primary pull-center" value='Grabar'>
         <button type="reset" class="btn btn-primary pull-center" >Borrar</button>
      </div>
    </div>
</fieldset> 
    <div class="control-group camposobligatorios">
      <p>*Campos Obligatorios</p>
    </div> 
</form>
<a class="btn btn-primary pull-center" href="javascript:history.back(1)">REGRESAR</a>
<br>
<br>
  