<form id="usuario" class="form-horizontal" action='<?= BASE_URL; ?>bombero/ingresar' method='post'>
  <fieldset>
  <legend>Ingresar Nuevo Bombero</legend>

    <div class="control-group">
      <label class="control-label" for="inputNOMBRE">NOMBRE *</label>
      <div class="controls">
        <input type="text" class="input-large"  id="inputNOMBRE" name='NOMBRE' required>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputAPELLIDOS">APELLIDOS *</label>
      <div class="controls">
        <input type="text" class="input-large"  id="inputAPELLIDOS" name='APELLIDOS' required>
      </div>
    </div> 
    <div class="control-group">
      <label class="control-label" for="inputEMAIL">EMAIL *</label>
      <div class="controls">
        <input type="email" class="input-large"  id="inputEMAIL" name='EMAIL' required>
      </div>
    </div>    
    <div class="control-group">
      <label class="control-label" for="inputROL">ROL</label>
      <div class="controls">
        <select name="ROL" required>
          <option selected >Seleccione</option>
          <option value="2">Administrador</option>
          <option value="3">Supervisor</option>s
        </select>
      </div>
    </div> 
    <div class="control-group">
      <label class="control-label" for="inputUBICACION">UBICACION</label>
      <br>
      <div class="controls">
        <div>
        <p>Departamento:</p>
          <select name='DEPARTAMENTO' id='departamento' readonly>
            <option selected value='15'>Lima</option>
            
          </select>
        </div>
        <div>
        <p>Provincia:</p>
          <select name='PROVINCIA' id='provincia' readonly> 
          <option selected value='01'>Lima</option>
          </select>
        </div>
        <div>
        <p>Distrito:</p>
          <select size='5'name='DISTRITO' id='distrito'>
          <option selected value='0'>Todos</option>
          <?php while($reg=$this->distritos->fetch_object()):?>
            <option value ='<?= $reg->District?>' ><?= $reg->NameUbigeo?></option>
            <?php endwhile;?>
          </select>
        </div>
      </div>
    </div>    
    <div class="control-group">
      <label class="control-label" for="inputACTIVO">ACTIVO</label>
      <div class="controls">
        <input type='checkbox' id="inputACTIVO" name='ACTIVO'>
      </div>
    </div>  
    <div class="control-group">
      <div class="controls">
        <input type='submit' class="btn btn-primary pull-center" value='Grabar'>
         <button type="reset" class="btn btn-primary pull-center" >Borrar</button>
      </div>
    </div>
</fieldset> 
    <div class="control-group camposobligatorios">
      <p>*Campos Obligatorios</p>
    </div> 
</form>
<a class="btn btn-primary pull-center" href="javascript:history.back(1)">REGRESAR</a>
<br>
<br>
  