<?php while ($reg = $this->alertas->fetch_object()): ?>
<tr>
	<td> <?=$reg->idAlert?> </td>
	<!-- <td> <?=$reg->Code?> </td> -->
	<td> <?=$reg->Date?> </td>
	<td> <?=$reg->Location?> </td>
	<td> <a href="<?= BASE_URL; ?>app-user/<?=$reg->PhoneNumberCaller?>"> <?=($reg->PhoneNumber=='--')?$reg->PhoneNumberCaller:$reg->PhoneNumber?> </a></td>
	<td> <?=$reg->AlertType?> </td>
	<td> <?=$reg->Plate?> </td>
	<td class="<?=$reg->State?>"> <?=$reg->State?></td>
	<td>
			<?php if($reg->idState=='1'):?>
			<a style="cursor:pointer" href="<?= BASE_URL; ?>alerta/atender/<?=$reg->idAlert?>"><img src="<?= $_layoutParams['ruta_img']?>Atender.png" class="opciones"alt="Atender" title="Atender"/></a>  
			<?php endif; ?>
			<?php if($reg->idState=='2' && Session::get('distrito')!='TODOS' ):?>
			<a style="cursor:pointer" href="<?= BASE_URL; ?>alerta/atender/<?=$reg->idAlert?>"><img src="<?= $_layoutParams['ruta_img']?>Atender.png" class="opciones"alt="Atender" title="Atender"/></a> 
			<?php endif; ?>
			<a style="cursor:pointer" href="<?= BASE_URL; ?>alerta/detalle/<?=$reg->idAlert?>"><img src="<?= $_layoutParams['ruta_img']?>Detalle.png" class="opciones"alt="Detalle" title="Detalle"/></a>
	</td>
</tr>
<?php endwhile;?>