<legend>Alertas Recibidas (<?=Session::get('numero')?>)</legend>
<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>ID</th>
			<th>FECHA</th>
			<th>UBICACIÓN</th>
			<th>NÚMERO</th>
			<th>EMERGENCIA</th>
			<th>UNIDAD</th>
			<th>ESTADO</th>
			<th>OPCIONES</th>		
		</tr>
	</thead>
	<tbody>
		<?php while ($reg = $this->alertas->fetch_object()): ?>
		<tr>
			<td> <?=$reg->idAlert?> </td>
			<td> <?=$reg->Date?> </td>
			<td> <?=$reg->Location?> </td>
			<td> <a href="<?= BASE_URL; ?>app-user/<?=$reg->PhoneNumberCaller?>"> <?=($reg->PhoneNumber=='--')?$reg->PhoneNumberCaller:$reg->PhoneNumber?> </a></td>
			<td> <?=$reg->AlertType?> </td>
			<td> <?=$reg->Plate?> </td>
			<td class="<?=$reg->State?>"> <?=$reg->State?></td>
			<td>
				<?php if($reg->idState=='1'):?>
				<a style="cursor:pointer" href="<?= BASE_URL; ?>alerta/atender/<?=$reg->idAlert?>"><img src="<?= $_layoutParams['ruta_img']?>Atender.png" class="opciones"alt="Atender" title="Atender"/></a>  
				<?php endif; ?>
				<?php if($reg->idState=='2' && Session::get('distrito')!='TODOS' ):?>
				<a style="cursor:pointer" href="<?= BASE_URL; ?>alerta/atender/<?=$reg->idAlert?>"><img src="<?= $_layoutParams['ruta_img']?>Atender.png" class="opciones"alt="Atender" title="Atender"/></a> 
				<?php endif; ?>
				<a style="cursor:pointer" href="<?= BASE_URL; ?>alerta/detalle/<?=$reg->idAlert?>"><img src="<?= $_layoutParams['ruta_img']?>Detalle.png" class="opciones"alt="Detalle" title="Detalle"/></a>
			</td>
		</tr>
		<?php endwhile;?>
	</tbody>
</table>
<!-- <div class="pagination">
	<ul>
		<li><a href="<?= BASE_URL; ?>alerta/alertas/<?=$this->param['anterior']?>">Anterior</a></li>
		<?php foreach ($this->param['rango'] as $pag):?>
		<li class=<?=($this->param['actual']==$pag)?'active':''?>><a href="<?= BASE_URL; ?>alerta/alertas/<?=$pag?>"><?= $pag?></a></li>
		<?php endforeach;?>	
		<li><a href="<?= BASE_URL; ?>alerta/alertas/<?=$this->param['siguiente']?>">Siguiente</a></li>
	</ul>
</div> -->
<br>
<a class="btn btn-primary pull-center" href="alertas">&laquo; REGRESAR</a>
<br>
<br>