<form id="alerta" class="form-horizontal hero-unit" action='<?= BASE_URL; ?>alerta/ingresarAlerta/' method='post'>
  <fieldset>
  <legend>DERIVAR ALERTA</legend>
  <legend>Datos Personales</legend>
    <input type="hidden" name='ID' id="ID" value ='<?= $this->alerta->idAlert ?>'>
    <input type="hidden" name='IDAPP' id="IDAPP" value ='<?= $this->alerta->idAppUser ?>'>
    <div class="control-group">
      <label class="control-label" for="inputNUMERO">NUMERO *</label>
      <div class="controls">
        <input autofocus type="text" class="input-large"  id="inputNUMERO" name='NUMERO' value="<?= ($this->alerta->PhoneNumber=='--')?$this->alerta->PhoneNumberCaller:$this->alerta->PhoneNumber ?>" required>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputNOMBRE">NOMBRES *</label>
      <div class="controls">
        <input autofocus type="text" class="input-large"  id="inputNOMBRE" name='NOMBRE' value ='<?= ($this->alerta->idAppUser=="1")?$this->alerta->NameCaller:$this->alerta->NameUser;?>' required>
      </div>
    </div>
    <legend>Datos de la Emergencia</legend>
    <div id="datos-emergencia">
    <div class="control-group">
      <label class="control-label" for="inputUBICACION">UBICACION *</label>
      <div class="controls">
          <!-- <div class="input"> -->
        <input type="text" class="input-large"  id="inputUBICACION" name='UBICACION' value ='<?= $this->alerta->Location ?>' required>
            <input type="button" id='submit'class="btn" value="Ubicar"/>
          <!-- </div> -->
      </div>
    </div>    
    <div class="control-group">
      <label class="control-label" for="inputTIPO">TIPO DE EMERGENCIA</label>
      <div class="controls">
        <select name="TIPO" size="5" required>
          <option selected value='<?= $this->alerta->idAlertType ?>'><?= $this->alerta->AlertType ?></option>
          <option value="3">Accidente Vehicular</option>
          <option value="4">Incendio</option>
          <option value="5">Emergencia Médica</option>
          <option value="6">Otros</option>
        </select>
      </div>
    </div> 
    <div class="control-group">
      <label class="control-label" for="inputDETALLE">DETALLE DE EMERGENCIA</label>
      <div class="controls">
        <textarea class="input-large" name="DETALLE" id="DETALLE" style="resize:none;"><?= $this->alerta->AlertDetail ?></textarea>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputDERIVAR">DERIVAR</label>
      <br>
      <div class="controls">

        <?php if((Session::get('distrito'))=="TODOS"):?>
        <div>
          <select name='DISTRITO' id='distrito' required>
          <option value="" selected>Seleccione el distrito</option>
          <?php while($reg=$this->distritos->fetch_object()):?>
            <option value='<?= $reg->District?>' ><?= $reg->NameUbigeo?></option>
            <?php endwhile;?>
              <?
        $unidades = array();

        ?>
          </select>
        </div>
         <?php endif; ?>

        <?php if( (Session::get('distrito'))!="TODOS"):?>
        <div>
          <select name='UNIDAD' id='unidad' required>
          <option selected value="" required>Seleccione la unidad</option>
          <?php while($reg2=$this->unidades->fetch_object()):?>
            <option value ='<?= $reg2->idAppUnit?>' ><?= $reg2->Plate?></option>
            <?php endwhile;?>
          </select>
        </div>
        <?
        $unidades = array();
        while($reg3=$this->unidadesL->fetch_object()):
          $p = explode(",", $reg3->LocationUnit);
          $unidades[] = array("placa"=>$reg3->Plate, "lat"=>$p[0], "lng"=>$p[1]);
        endwhile;
        ?>
        <?php endif; ?>
      </div>
    </div>    
    </div>
    <div id="mapa"></div>
</fieldset> 
    <div class="control-group camposobligatorios">
      <p>*Campos Obligatorios</p>
    </div> 
    <figure class="inline" style="text-align:center;">
      <input type='image' title="Guardar Campos" src="<?= $_layoutParams['ruta_img']?>Guardar.png" class="botones" value='Grabar'>
      <figcaption><label>DERIVAR</label></figcaption>
      </figure>
      <figure class="inline" style="text-align:center;">
      <a href="javascript:document.getElementById('usuario').reset();"><img title="Limpiar" src="<?= $_layoutParams['ruta_img']?>Limpiar.png" class="botones" alt='Limpiar'></a>
      <figcaption><label>LIMPIAR CAMPOS</label></figcaption>
      </figure>
      <figure class="inline"style="text-align:center;">
      <a class="botones" href="javascript:history.back(1)"><img title="Volver" src="<?= $_layoutParams['ruta_img']?>Volver.png" class="botones" alt='Volver'></a>
      <figcaption><label>VOLVER A ATRÁS</label></figcaption>
      </figure>
</form>  
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?region=PE,sensor=true">
</script>
<script type="text/javascript">

var geocoder;
var map;

function initialize() {
  geocoder = new google.maps.Geocoder();
  
  var mapOptions = {
    zoom: 12,
    center: new google.maps.LatLng(-12.071578932615392, -76.95683059406736)
  }

  map = new google.maps.Map(document.getElementById('mapa'), mapOptions);

  setMarkers(map, beaches);
}

var u = $.parseJSON(<?php print(json_encode(json_encode($unidades))); ?>); 
var beaches=[];

for(var i=0;i<u.length;i++)
{
  beaches[i] = [
    u[i]['placa'], parseFloat(u[i]['lat']),parseFloat(u[i]['lng'])
  ];
}

var image = {
  url: '../../views/layout/default/img/unidb.png',
  size: new google.maps.Size(30, 42),
  origin: new google.maps.Point(0,0),
  anchor: new google.maps.Point(0, 42)
};

var shape = {
  coords: [1, 1, 1, 30, 28, 30, 28 , 1],
  type: 'poly'
};
var infowindow = new google.maps.InfoWindow();

function setMarkers(map, locations) {

  for (var i = 0; i < locations.length; i++) {
    var beach = locations[i];
    var myLatLng = new google.maps.LatLng(beach[1],beach[2]);
    var n="marker"+[i];
    n = new google.maps.Marker({
      position: myLatLng,
      map: map,
      icon: image,
      shape: shape,
      title: 'UNIDAD'+'\n'+beach[0]
    });

    google.maps.event.addListener(n, 'click', function() {
      infowindow.setContent('<p>UNIDAD: '+beach[0]+'</p>');
      infowindow.open(map,this);
    });

// infowindow.open(map, n);
// google.maps.event.addListener(n, 'click', toggleBounce);
// function toggleBounce() {
//   if (n.getAnimation() != null) {
//     n.setAnimation(null);
//   } else {
//     n.setAnimation(google.maps.Animation.BOUNCE);
//   }
// }s
  }
}

$('#submit').click(function(e) {

  e.preventDefault();
  var address = $('#inputUBICACION').val();
  geocoder.geocode( { 'address': address}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) {
      map.setCenter(results[0].geometry.location);
      var info = new google.maps.InfoWindow({
      content: '<p>EMERGENCIA</p>'
      });
      var nuevo = new google.maps.Marker({
        map: map,
        animation: google.maps.Animation.DROP,
        draggable: true,
        position: results[0].geometry.location
      });
      
      google.maps.event.addListener(nuevo, 'click', function() {
        info.open(map,nuevo);
      });

    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });

});

// function loadScript() {
//   var script = document.createElement('script');
//   script.type = 'text/javascript';
//   script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp&' +
//       'callback=initialize';
//   document.body.appendChild(script);
// }
google.maps.event.addDomListener(window, 'load', initialize);
// window.onload = loadScript;
</script>