<form id="alerta" class="form-horizontal hero-unit" action='<?= BASE_URL; ?>alerta/ingresarAlerta/' method='post'>
  <fieldset>
  <legend>NUEVA ALERTA</legend>
  <legend>Datos Personales</legend>
    <div class="control-group">
      <label class="control-label" for="inputNUMERO">NUMERO *</label>
      <div class="controls">
        <input autofocus type="text" class="input-large"  id="inputNUMERO" name='NUMERO' required>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputNOMBRE">NOMBRES *</label>
      <div class="controls">
        <input autofocus type="text" class="input-large"  id="inputNOMBRE" name='NOMBRE' required>
      </div>
    </div>
    <legend>Datos de la Emergencia</legend>
     <div id="datos-emergencia">
    <div class="control-group">
      <label class="control-label" for="inputUBICACION">UBICACION *</label>
      <div class="controls">
        <input type="text" class="input-large"  id="inputUBICACION" name='UBICACION' required>
         <input type="submit" id='submit'class="btn" value="Ubicar" />
      </div>
    </div> 
    <div class="control-group">
      <label class="control-label" for="inputTIPO">TIPO DE EMERGENCIA</label>
      <div class="controls">
        <select name="TIPO" required>
          <option selected value="">Seleccione</option>
          <option value="3">Accidente Vehicular</option>
          <option value="4">Incendio</option>
          <option value="5">Emergencia Médica</option>
          <option value="6">Otros</option>
        </select>
      </div>
    </div> 
    <div class="control-group">
      <label class="control-label" for="inputDETALLE">DETALLE DE EMERGENCIA</label>
      <div class="controls">
        <textarea class="input-large" name="DETALLE" id="DETALLE" style="resize:none;"></textarea>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputDERIVAR">DERIVAR</label>
      <br>
      <div class="controls">

        <?php if((Session::get('distrito'))=="TODOS"):?>
        <div>
        <p>Distrito:</p>
          <select name='DISTRITO' id='distrito' required>
          <option selected >Seleccione el distrito</option>
          <?php while($reg=$this->distritos->fetch_object()):?>
            <option value ='<?= $reg->District?>' ><?= $reg->NameUbigeo?></option>
            <?php endwhile;?>
          </select>
        </div>
         <?php endif; ?>

        <?php if( (Session::get('distrito'))!="TODOS"):?>
        <div>
        <p>Unidad:</p>
          <select name='UNIDAD' id='unidad' required>
          <option selected>Seleccione la unidad</option>
          <?php while($reg2=$this->unidades->fetch_object()):?>
            <option value ='<?= $reg2->idAppUnit?>' ><?= $reg2->Plate?></option>
            <?php endwhile;?>
          </select>
        </div>
        <?php endif; ?>
      </div>
    </div>    
    </div>
    <div id="mapa"></div>
</fieldset> 
    <div class="control-group camposobligatorios">
      <p>*Campos Obligatorios</p>
    </div> 
    <figure class="inline" style="text-align:center;">
      <input type='image' title="Guardar Campos" src="<?= $_layoutParams['ruta_img']?>Guardar.png" class="botones" value='Grabar'>
      <figcaption><label>DERIVAR</label></figcaption>
      </figure>
      <figure class="inline" style="text-align:center;">
      <a href="javascript:document.getElementById('usuario').reset();"><img title="Limpiar" src="<?= $_layoutParams['ruta_img']?>Limpiar.png" class="botones" alt='Limpiar'></a>
      <figcaption><label>LIMPIAR CAMPOS</label></figcaption>
      </figure>
      <figure class="inline"style="text-align:center;">
      <a class="botones" href="javascript:history.back(1)"><img title="Volver" src="<?= $_layoutParams['ruta_img']?>Volver.png" class="botones" alt='Volver'></a>
      <figcaption><label>VOLVER A ATRÁS</label></figcaption>
      </figure>
</form>