<legend><h2>Departamento de Policías</h2></legend>
<br>
<div class="hero-unit">
	<div class="datos">
		<ul>
			<li><a href="policia/administradores">ADMINISTRADORES</a></li>
			<li><a href="policia/supervisores">SUPERVISORES</a></li>
			<li><a href="policia/nuevo">INGRESAR NUEVO POLICIA</a></li>
		</ul>		
	</div>
	<div class="foto">
		<img src="<?= $_layoutParams['ruta_img']?>pnp.jpg" height="200px" width="180px" alt="Escudo de Policía">
	</div>
		
</div>
<br>