<legend><h2>Mi Cuenta</h2></legend>
<br>
<div class="hero-unit">
	<figure class="inline"style="text-align:center;">
		<a href="detalle/<?=Session::get('id')?>"><img class="iconos"src="<?= $_layoutParams['ruta_img']?>Profile.png" alt="Detalle Usuario" title='Detalle del Usuario'/></a>
		<figcaption><label>DETALLE</label></figcaption>
	</figure>
	<figure class="inline"style="text-align:center;">
		<a href="estadistica"><img class="iconos" src="<?= $_layoutParams['ruta_img']?>Estadistica.png" alt="Estadisticas" title='Estadísticas'/></a>
		<figcaption><label>ESTADÍSTICAS</label></figcaption>
	</figure>
	<figure class="inline"style="text-align:center;">
		<a href="password"><img class="iconos" src="<?= $_layoutParams['ruta_img']?>Password.png" alt="Password" title='Cambiar contraseña'/></a>
		<figcaption><label>CAMBIAR CONTRASEÑA</label></figcaption>
	</figure>
<!-- <div class="image">

<a href="estadistica"><img src="<?= $_layoutParams['ruta_img']?>Estadistica.png" alt="Estadisticas" title='Estadísticas'/></a>

 <h2 class="h2img"><span class="spanimg">STATISTICS</span></h2>
</div> -->

</div>
<br>