<legend>Detalle Usuario</legend>

<table class="table table-bordered table-striped">
	<col style="width: 200px" />
	<col style="width: 100px" span="3" />
	<tr>
		<th scope="row">ID</th>
		<td><?= $this->usuario->idUser ?></td>
	</tr>
	<tr>
		<th scope="row">CÓDIGO</th>
		<td><?= $this->usuario->Code?></td>
	</tr>
	<tr>
		<th scope="row">NOMBRE</th>
		<td><?= $this->usuario->Name?></td>
	</tr>
	<tr>
		<th scope="row">APELLIDOS</th>
		<td><?= $this->usuario->LastName?></td>
	</tr>
	<tr>
		<th scope="row">NOMBRE DE USUARIO</th>
		<td><?= $this->usuario->User?></td>
	</tr>
	<tr>
		<th scope="row">EMAIL</th>
		<td><?= $this->usuario->Email?></td>
	</tr>
	<tr>
		<th scope="row">FECHA DE REGISTRO</th>
		<td><?= $this->usuario->RegistrationDate?></td>
	</tr>
	<tr>
		<th scope="row">FECHA DE MODIFICACIÓN</th>
		<td><?= $this->usuario->UpdateDate?></td>
	</tr>
	<tr>
		<th scope="row">ESTADO</th>
		<td><?=$this->usuario->State?'ACTIVO':'INACTIVO'?></td>
	</tr>
	<tr>
		<th scope="row">CENTRAL</th>
		<td><?=$this->usuario->UserType?></td>
	</tr>	
	<tr>
		<th scope="row">ROL</th>
		<td><?= $this->usuario->Role?> - <?= $this->usuario->DetailRole?></td>
	</tr>
	<tr>
		<th scope="row">DEPARTAMENTO / PROVINCIA / DISTRITO</th>
		<td><?= $this->usuario->Department?>-<?= $this->usuario->Province?>-<?= $this->usuario->District?></td>
	</tr>
</table>

<figure class="inline"style="text-align:center;">
	<a href="estadistica"><img class="botones" src="<?= $_layoutParams['ruta_img']?>Volver.png" alt="Volver" title='Volver'/></a>
	<figcaption><label>VOLVER</label></figcaption>
</figure>
<figure class="inline"style="text-align:center;">
	<a href="<?= BASE_URL?>usuario/editar/<?= $this->usuario->idUser ?>"><img class="botones"src="<?= $_layoutParams['ruta_img']?>Editar.png" alt="editar Usuario" title='Editar Usuario'/></a>
	<figcaption><label>EDITAR</label></figcaption>
</figure>		
