<form id="unidad" class="form-horizontal formulario hero-unit" action='<?= BASE_URL; ?>usuario/ingresar' method='post' enctype="multipart/form-data">
  <fieldset>
  <legend>Editar Usuario </legend>
  <div class="inline">
    	 <input type="hidden" class="input-small"  id="inputID" name='ID' value ='<?= $this->usuario->idUser ?>' readonly>
  	
    <div class="control-group">
      <label class="control-label" for="inputNOMBRE">NOMBRE *</label>
      <div class="controls">
        <input type="text" class="input-large"  id="inputNOMBRE" name='NOMBRE' value='<?= $this->usuario->Name?>'required>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputAPELLIDOS">APELLIDOS *</label>
      <div class="controls">
        <input type="text" class="input-large"  id="inputAPELLIDOS" name='APELLIDOS' value='<?= $this->usuario->LastName?>'required>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputEMAIL">EMAIL *</label>
      <div class="controls">
        <input type="email" class="input-large"  id="inputEMAIL" name='EMAIL' value='<?= $this->usuario->Email?>'required>
      </div>
    </div>   
     <?php if(Session::get('rol')=='Administrador'):?>
    <div class="control-group">
      <label class="control-label" for="inputCLAVE">CLAVE *</label>
      <div class="controls">
        <input type="password" class="input-small"  id="inputCLAVE" name='CLAVE' value"">
      </div>
    </div>   
 
    <div class="control-group">
      <label class="control-label" for="inputROL">ROL</label>
      <div class="controls">
        <select name="ROL">
          <option value='<?= $this->usuario->idRole?>'><?= $this->usuario->DetailRole?></option>
          <option value="2">Administrador</option>
          <option value="3">Supervisor</option>s
        </select>
      </div>
    </div> 
    <div class="control-group">
      <label class="control-label" for="inputACTIVO">ACTIVO</label>
        <div class="controls">
            <input type='checkbox' id="inputACTIVO" name='ACTIVO' <?php if($this->usuario->State==1)echo "checked";?> >
        </div>
    </div>   
     <?php endif;?>
    <?php if(Session::get('tipoId')=='1'):?>
     <div class="control-group">
      <label class="control-label" for="inputUBICACION">UBICACION</label>
      <br>
      <div class="controls">
        <div>
        <p>Departamento:</p>
          <select name='DEPARTAMENTO' id='departamento' readonly>
            <option selected value="15">Lima</option>
            
          </select>
        </div>
        <div>
        <p>Provincia:</p>
          <select name='PROVINCIA' id='provincia' readonly> 
          <option selected value="01">Lima</option>
          </select>
        </div>
        <div>
        <p>Distrito:</p>
          <select size='5'name='DISTRITO' id='distrito'>
          <option selected value='0' >Todos</option>
          <?php while($reg=$this->distritos->fetch_object()):?>
            <option value ='<?= $reg->District?>' ><?= $reg->NameUbigeo?></option>
            <?php endwhile;?>
          </select>
        </div>
      </div>
    </div>   
        <?php endif;?>
    <div class="control-group camposobligatorios">
      <p>*Campos Obligatorios</p>
    </div> 
    </div>
    <div class="opciones-form">
      <figure style="text-align:center;">
      <input type='image' title="Guardar" src="<?= $_layoutParams['ruta_img']?>Guardar.png" class="botones" value='Grabar'>
      <figcaption><label>ACTUALIZAR</label></figcaption>
      </figure>
      <figure style="text-align:center;">
      <a class="botones" href="javascript:history.back(1)"><img title="Volver" src="<?= $_layoutParams['ruta_img']?>Volver.png" class="botones" alt='Volver'></a>
      <figcaption><label>VOLVER A ATRÁS</label></figcaption>
      </figure>
    </div>
</fieldset> 
</form>