<form class="form-horizontal hero-unit formulario" id='client-form' action='<?= BASE_URL; ?>usuario/cambiarPassword' method='post'>
  <fieldset>
  <legend>Cambiar contraseña </legend>
  <div class="inline">
<div id="error"><p><?php if(isset($this->_error)) echo $this->_error;?></p></div>
  	<div class="control-group">
    	<label class="control-label" for="ANTIGUO">CONTRASEÑA ANTERIOR *</label>
  		<div class="controls">
    	 <input type="password" class="input-large"  name="ANTIGUO" id="ANTIGUO">
  		</div>
    </div>
    <div class="control-group">
      <label class="control-label" for="password">NUEVA CONTRASEÑA *</label>
      <div class="controls">
        <input id="password" class="input-large password" name="password" type="password" maxlength="30" value="" />
	  		<div class="password-meter">
				<div class="password-meter-message">&nbsp;</div>
				<div class="password-meter-bg">
					<div class="password-meter-bar"></div>
				</div>
	      </div>
			</div>
    </div>
    <div class="control-group">
      <label class="control-label" for="password_confirm">REPETIR NUEVA CONTRASEÑA *</label>
      <div class="controls">
        <input id="password_confirm" class="input-large" name="password_confirm" type="password" maxlength="30" value="" />
      </div>
    </div>
    <div class="control-group camposobligatorios">
      <p>*Campos Obligatorios</p>
    </div> 
    </div>
    <div class="opciones-form">
      <figure style="text-align:center;">
      <input type='image' title="Guardar Campos" src="<?= $_layoutParams['ruta_img']?>Guardar.png" class="botones" value='Grabar'>
      <figcaption><label>ACTUALIZAR</label></figcaption>
      </figure>
      <figure style="text-align:center;">
      <a class="botones" href="javascript:history.back(1)"><img title="Volver" src="<?= $_layoutParams['ruta_img']?>Volver.png" class="botones" alt='Volver'></a>
      <figcaption><label>VOLVER A ATRÁS</label></figcaption>
      </figure>
    </div>
   </fieldset> 
</form>