<form id="usuario" class="form-horizontal" action='<?= BASE_URL; ?>appuser/ingresar' method='post'>
  <fieldset>
  <legend>Ingresar Nuevo Usuario</legend>

    <div class="control-group">
      <label class="control-label" for="inputNOMBRE">NOMBRE *</label>
      <div class="controls">
        <input type="text" class="input-large"  id="inputNOMBRE" name='NOMBRE' required>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputAPELLIDOS">APELLIDOS *</label>
      <div class="controls">
        <input type="text" class="input-large"  id="inputAPELLIDOS" name='APELLIDOS' required>
      </div>
    </div> 
    <div class="control-group">
      <label class="control-label" for="inputNUMERO">NÚMERO *</label>
      <div class="controls">
        <input type="number" min='1' max='999999999'class="input-large"  id="inputNUMERO" name='NUMERO' required>
      </div>
    </div>    
    <div class="control-group">
      <label class="control-label" for="inputDNI">DNI *</label>
      <div class="controls">
      <input type="number" min='1' max='99999999'class="input-large"  id="inputDNI" name='DNI' required>
      </div>
    </div> 
      <div class="controls">
        <input type='submit' class="btn btn-primary pull-center" value='Grabar'>
         <button type="reset" class="btn btn-primary pull-center" >Borrar</button>
      </div>
</fieldset> 
    <div class="control-group camposobligatorios">
      <p>*Campos Obligatorios</p>
    </div> 
</form>
<a class="btn btn-primary pull-center" href="javascript:history.back(1)">REGRESAR</a>
<br>
<br>
  