<legend><h2>Bienvenido </h2></legend>
<br>
<div class="hero-unit">
	<div class="datos">
		<p>Nombres: <?=Session::get('usuario')?> <?=Session::get('apellidos')?></p>
		<p>Puesto : <?=Session::get('tipo')?></p>
		<p>Rol: <?=Session::get('rol')?></p>
		<p><?=Session::get('idDepartamento')?>-<?=Session::get('idProvincia')?>-<?=Session::get('idDistrito')?></p>
		<p>Distrito: <?=Session::get('distrito')?></p>
	</div>
	<div class="foto">
		<img src="<?= $_layoutParams['ruta_img']?>user.png" height="100px" width="100px" alt="usuario">
	</div>
		
</div>
<br>