<form class="form-horizontal" id='client-form' action='<?= BASE_URL; ?>usuario/cambiarPassword' method='post' enctype="multipart/form-data">
  <fieldset>
  <legend>Cambiar contraseña </legend>
  	<div class="control-group">
    	<label class="control-label" for="ANTIGUO">CONTRASEÑA ANTERIOR *</label>
  		<div class="controls">
    	 <input type="password" class="input-large"  name="ANTIGUO" id="ANTIGUO">
  		</div>
  		<br>
    </div>
    <div class="control-group">
      <label class="control-label" for="password">NUEVA CONTRASEÑA *</label>
      <div class="controls">
        <input id="password" class="input-large password" name="password" type="password" maxlength="30" value="" />
	  		<div class="password-meter">
				<div class="password-meter-message">&nbsp;</div>
				<div class="password-meter-bg">
					<div class="password-meter-bar"></div>
				</div>
	      </div>
			</div>
    </div>
    <div class="control-group">
      <label class="control-label" for="password_confirm">REPETIR NUEVA CONTRASEÑA *</label>
      <div class="controls">
        <input id="password_confirm" class="input-large" name="password_confirm" type="password" maxlength="30" value="" />
      </div>
    </div>
    <div class="control-group camposobligatorios">
      <p>*Campos Obligatorios</p>
    </div> 
      <input type='submit' class="btn btn-primary pull-center" value='Cambiar'>
   </fieldset> 
</form>
<a class="btn btn-primary pull-center" href="javascript:history.back(1)">REGRESAR</a>
<br>
<br>